const kpiArray = [
   {
      "orders":218,
      "precision":87.00,
      "accidents":3
   },
   {
      "orders":231,
      "precision":75.00,
      "accidents":0
   },
   {
      "orders":292,
      "precision":96.00,
      "accidents":1
   },
   {
      "orders":140,
      "precision":77.00,
      "accidents":0
   },
   {
      "orders":199,
      "precision":73.00,
      "accidents":0
   },
   {
      "orders":268,
      "precision":95.00,
      "accidents":0
   },
   {
      "orders":276,
      "precision":81.00,
      "accidents":0
   },
   {
      "orders":103,
      "precision":88.00,
      "accidents":0
   },
   {
      "orders":46,
      "precision":95.00,
      "accidents":1
   },
   {
      "orders":119,
      "precision":88.00,
      "accidents":0
   },
   {
      "orders":72,
      "precision":75.00,
      "accidents":2
   },
   {
      "orders":82,
      "precision":81.00,
      "accidents":0
   },
   {
      "orders":38,
      "precision":77.00,
      "accidents":1
   },
   {
      "orders":275,
      "precision":94.00,
      "accidents":0
   },
   {
      "orders":30,
      "precision":74.00,
      "accidents":0
   },
   {
      "orders":75,
      "precision":72.00,
      "accidents":1
   },
   {
      "orders":150,
      "precision":81.00,
      "accidents":0
   },
   {
      "orders":34,
      "precision":85.00,
      "accidents":4
   },
   {
      "orders":98,
      "precision":95.00,
      "accidents":0
   },
   {
      "orders":250,
      "precision":98.00,
      "accidents":0
   },
   {
      "orders":161,
      "precision":85.00,
      "accidents":0
   },
   {
      "orders":54,
      "precision":84.00,
      "accidents":0
   },
   {
      "orders":60,
      "precision":90.00,
      "accidents":1
   },
   {
      "orders":110,
      "precision":77.00,
      "accidents":0
   },
   {
      "orders":123,
      "precision":73.00,
      "accidents":0
   },
   {
      "orders":44,
      "precision":80.00,
      "accidents":5
   },
   {
      "orders":54,
      "precision":92.00,
      "accidents":0
   },
   {
      "orders":233,
      "precision":87.00,
      "accidents":0
   },
   {
      "orders":244,
      "precision":89.00,
      "accidents":1
   },
   {
      "orders":213,
      "precision":98.00,
      "accidents":0
   },
   {
      "orders":154,
      "precision":74.00,
      "accidents":0
   },
   {
      "orders":77,
      "precision":85.00,
      "accidents":0
   },
   {
      "orders":292,
      "precision":94.00,
      "accidents":1
   },
   {
      "orders":246,
      "precision":87.00,
      "accidents":0
   },
   {
      "orders":175,
      "precision":96.00,
      "accidents":1
   },
   {
      "orders":82,
      "precision":80.00,
      "accidents":0
   },
   {
      "orders":164,
      "precision":82.00,
      "accidents":0
   },
   {
      "orders":278,
      "precision":79.00,
      "accidents":0
   },
   {
      "orders":44,
      "precision":91.00,
      "accidents":3
   },
   {
      "orders":105,
      "precision":95.00,
      "accidents":0
   },
   {
      "orders":279,
      "precision":89.00,
      "accidents":0
   },
   {
      "orders":128,
      "precision":78.00,
      "accidents":0
   },
   {
      "orders":187,
      "precision":71.00,
      "accidents":0
   },
   {
      "orders":235,
      "precision":74.00,
      "accidents":0
   },
   {
      "orders":252,
      "precision":94.00,
      "accidents":0
   },
   {
      "orders":71,
      "precision":98.00,
      "accidents":0
   },
   {
      "orders":158,
      "precision":71.00,
      "accidents":0
   },
   {
      "orders":215,
      "precision":73.00,
      "accidents":0
   },
   {
      "orders":253,
      "precision":70.00,
      "accidents":1
   },
   {
      "orders":96,
      "precision":93.00,
      "accidents":0
   },
   {
      "orders":168,
      "precision":98.00,
      "accidents":0
   },
   {
      "orders":267,
      "precision":96.00,
      "accidents":1
   },
   {
      "orders":94,
      "precision":100.00,
      "accidents":0
   },
   {
      "orders":269,
      "precision":89.00,
      "accidents":1
   },
   {
      "orders":98,
      "precision":91.00,
      "accidents":0
   },
   {
      "orders":65,
      "precision":93.00,
      "accidents":0
   },
   {
      "orders":93,
      "precision":77.00,
      "accidents":0
   },
   {
      "orders":154,
      "precision":96.00,
      "accidents":0
   },
   {
      "orders":284,
      "precision":71.00,
      "accidents":1
   },
   {
      "orders":240,
      "precision":98.00,
      "accidents":0
   },
   {
      "orders":191,
      "precision":80.00,
      "accidents":0
   },
   {
      "orders":87,
      "precision":95.00,
      "accidents":1
   },
   {
      "orders":92,
      "precision":88.00,
      "accidents":2
   },
   {
      "orders":214,
      "precision":99.00,
      "accidents":0
   },
   {
      "orders":236,
      "precision":78.00,
      "accidents":0
   },
   {
      "orders":83,
      "precision":72.00,
      "accidents":0
   },
   {
      "orders":145,
      "precision":95.00,
      "accidents":0
   },
   {
      "orders":259,
      "precision":91.00,
      "accidents":0
   },
   {
      "orders":167,
      "precision":99.00,
      "accidents":1
   },
   {
      "orders":197,
      "precision":96.00,
      "accidents":0
   },
   {
      "orders":53,
      "precision":97.00,
      "accidents":0
   },
   {
      "orders":268,
      "precision":85.00,
      "accidents":0
   },
   {
      "orders":78,
      "precision":77.00,
      "accidents":1
   },
   {
      "orders":225,
      "precision":84.00,
      "accidents":0
   },
   {
      "orders":186,
      "precision":76.00,
      "accidents":0
   },
   {
      "orders":261,
      "precision":94.00,
      "accidents":0
   },
   {
      "orders":78,
      "precision":73.00,
      "accidents":0
   },
   {
      "orders":175,
      "precision":77.00,
      "accidents":0
   },
   {
      "orders":30,
      "precision":89.00,
      "accidents":0
   },
   {
      "orders":253,
      "precision":92.00,
      "accidents":0
   },
   {
      "orders":251,
      "precision":84.00,
      "accidents":0
   },
   {
      "orders":189,
      "precision":91.00,
      "accidents":0
   },
   {
      "orders":82,
      "precision":91.00,
      "accidents":0
   },
   {
      "orders":46,
      "precision":74.00,
      "accidents":0
   },
   {
      "orders":253,
      "precision":99.00,
      "accidents":0
   },
   {
      "orders":67,
      "precision":76.00,
      "accidents":0
   },
   {
      "orders":292,
      "precision":96.00,
      "accidents":1
   },
   {
      "orders":168,
      "precision":94.00,
      "accidents":0
   },
   {
      "orders":239,
      "precision":75.00,
      "accidents":0
   },
   {
      "orders":292,
      "precision":80.00,
      "accidents":0
   },
   {
      "orders":206,
      "precision":77.00,
      "accidents":0
   },
   {
      "orders":100,
      "precision":99.00,
      "accidents":1
   },
   {
      "orders":228,
      "precision":73.00,
      "accidents":1
   },
   {
      "orders":265,
      "precision":90.00,
      "accidents":1
   },
   {
      "orders":154,
      "precision":78.00,
      "accidents":1
   },
   {
      "orders":201,
      "precision":91.00,
      "accidents":0
   },
   {
      "orders":185,
      "precision":95.00,
      "accidents":0
   },
   {
      "orders":244,
      "precision":70.00,
      "accidents":0
   },
   {
      "orders":218,
      "precision":93.00,
      "accidents":1
   },
   {
      "orders":178,
      "precision":82.00,
      "accidents":0
   },
   {
      "orders":64,
      "precision":73.00,
      "accidents":0
   },
   {
      "orders":118,
      "precision":95.00,
      "accidents":0
   },
   {
      "orders":48,
      "precision":94.00,
      "accidents":0
   },
   {
      "orders":158,
      "precision":92.00,
      "accidents":0
   },
   {
      "orders":86,
      "precision":100.00,
      "accidents":0
   },
   {
      "orders":54,
      "precision":88.00,
      "accidents":1
   },
   {
      "orders":102,
      "precision":85.00,
      "accidents":0
   },
   {
      "orders":41,
      "precision":80.00,
      "accidents":0
   },
   {
      "orders":206,
      "precision":90.00,
      "accidents":0
   },
   {
      "orders":247,
      "precision":78.00,
      "accidents":0
   },
   {
      "orders":224,
      "precision":91.00,
      "accidents":0
   },
   {
      "orders":198,
      "precision":74.00,
      "accidents":1
   },
   {
      "orders":44,
      "precision":79.00,
      "accidents":0
   },
   {
      "orders":175,
      "precision":70.00,
      "accidents":0
   },
   {
      "orders":286,
      "precision":88.00,
      "accidents":1
   },
   {
      "orders":241,
      "precision":87.00,
      "accidents":0
   },
   {
      "orders":111,
      "precision":88.00,
      "accidents":0
   },
   {
      "orders":71,
      "precision":80.00,
      "accidents":0
   },
   {
      "orders":192,
      "precision":87.00,
      "accidents":0
   },
   {
      "orders":205,
      "precision":76.00,
      "accidents":0
   },
   {
      "orders":214,
      "precision":88.00,
      "accidents":1
   },
   {
      "orders":139,
      "precision":84.00,
      "accidents":0
   },
];
kpiArray.forEach((item, i) => {
   var date = new Date();
   date.setDate(date.getDate() - i);
   item.date = date;
}); 
export default kpiArray;